// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqbkqmiktvwazmvrllnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xYmtxbWlrdHZ3YXptdnJsbG5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMDAxMDIsImV4cCI6MjA2Nzc3NjEwMn0.CLnRGjrFtFPHbackVvK23FLx4AAQh5sLuV24BAPkrOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});